# Generated by Django 4.2.30 on 2026-06-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_name_product_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(default=' ', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='isbn',
            field=models.CharField(default='unkown', max_length=13),
            preserve_default=False,
        ),
    ]
