# Generated by Django 4.2.30 on 2026-06-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_order_shipping_address_order_shipping_address_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shippping_address_country',
            new_name='shipping_address_country',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipping_address',
            new_name='shipping_address_line1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shippping_address_postcode',
            new_name='shipping_address_postcode',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address_line2',
            field=models.CharField(default='', max_length=200),
        ),
    ]
