# Generated by Django 4.2.30 on 2026-06-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_shippping_address_country_order_shipping_address_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address_city',
            field=models.CharField(default='', max_length=200),
        ),
    ]
