# Generated by Django 4.2.30 on 2026-06-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_order_shipping_address_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_address_city',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address_country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address_line1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address_line2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address_postcode',
            field=models.CharField(default='', max_length=20),
        ),
    ]
