# Generated by Django 4.2.30 on 2026-06-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_order_price_order_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='title',
            field=models.CharField(default='', max_length=254),
        ),
    ]
